#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export NVM_LAZY_LOAD=true
source ~/.zsh-nvm/zsh-nvm.plugin.zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

stty -ixon
unalias rm
unsetopt share_history
setopt clobber

mkdircd() {
  mkdir -p -- "$1" &&
  cd -P -- "$1"
}

parallel_download() {
  lftp -e "pget -n 5 -c $1 exit"
}

fpath=(~/xing-scripts/completion/zsh $fpath)

alias dropbox_encrypted_mount="cryfs /opt/Dropbox/encrypted_do_not_touch ~/Dropbox_encrypted"
alias aptgetupdateshit="sudo apt update && sudo apt dist-upgrade"
alias cdi="cd ~/work/ytpacks"

alias v="vim"
alias vi="vim -u NONE"
alias g="git"

alias zc='bundle exec rails c'
alias zs='bundle exec rails s'
