#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias dropbox_encrypted_mount="cryfs ~/Dropbox/encrypted_do_not_touch ~/Dropbox_encrypted"
alias aptgetupdateshit="sudo apt update ; sudo apt dist-upgrade"
alias cdi="cd ~/code/bytecash"

alias v="vim"
alias g="git"

stty -ixon
unalias rm

mkdircd() {
  mkdir -p -- "$1" &&
  cd -P -- "$1"
}
